Add Convenience Methods for Details
ParticleHealth/tau pull request #22
Opened 2021-06-11 17:33 UTC by seantan22

- adds `type Fields map[string]interface{}`
- adds support for adding a single detail to a slog entry

2021-06-14 19:02 UTC, Orbz requested changes

2021-06-14 20:11 UTC, seantan22 commented on slog/slog.go
> +	Err            string            `json:"error,omitempty"`
unable to name "Error" because method of same name exists

2021-06-15 13:09 UTC, Orbz requested changes

2021-06-15 13:09 UTC, Orbz commented on slog/slog.go
> +	Err            string            `json:"error,omitempty"`
Err can be type `error` I believe.

2021-06-15 13:09 UTC, Orbz commented on slog/slog.go
> +func (e *Entry) WithError(err string) *Entry {
Should take `error` instead of `string` for type safety.

2021-06-15 14:27 UTC, Orbz approved these changes

2021-06-15 14:51 UTC, merged