Add Examples to Package Documentation
ParticleHealth/tau pull request #25
Opened 2021-07-19 19:16 UTC by seantan22

Closes #23 

Adds the following examples to the slog package documentation.
![Screen Shot 2021-07-19 at 3 16 16 PM](https://user-images.githubusercontent.com/46289281/126214643-f1b12615-72f1-47fa-92d0-c11b64cedfe8.png)

2021-07-19 23:32 UTC, Orbz requested changes

2021-07-19 23:32 UTC, Orbz commented on slog/slog_test.go
> +// Examples
As far as I can tell idiomatic approach is to split this off into an `example_test.go` file.

2021-07-19 23:32 UTC, Orbz commented on slog/slog_test.go
> +	fmt.Print(got.Details["id"])
For these I don't think it makes much sense to `fmt.Print` various internal details, as that isn't how people are going to interact with the libraries. Probably should remove the `// Output:` sections and use `entry.Info("entry pulled from context")`. Where possible we should strive to have examples be functional if copied and pasted into a consumer's code base.

Same comment for all the below instances.

2021-07-20 15:23 UTC, seantan22 commented
@Orbz Updated tests to be more functional -- are there any functions that I've missed that you think I should include examples for?

2021-07-20 19:53 UTC, Orbz approved these changes
Nice job! Looks great.

2021-07-20 19:53 UTC, Orbz commented on slog/example_test.go
> +func ExampleNewContext() {
I'd combine `ExampleNewContext` and `ExampleFromContext` to show the full end to end.

2021-07-20 19:53 UTC, Orbz commented on slog/example_test.go
> +func ExampleStartOperation() {
I'd combine with `ExampleWithOperation` and also show `EndOperation`

2021-07-20 19:53 UTC, Orbz commented on slog/example_test.go
> +func ExampleWithDetail() {
I'd combine with `ExampleWithDetails`

2021-07-20 21:56 UTC, Orbz approved these changes

2021-07-20 23:00 UTC, merged